In [1]:
# coding: utf-8
import sys, os
sys.path.append(os.pardir)  # 부모 디렉터리의 파일을 가져올 수 있도록 설정
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [2]:

class simpleNet:
    def __init__(self):
        # 2*3 짜리 weight 행렬 랜덤 생성
        self.W = np.random.randn(2,3) # 정규분포로 초기화

    # x = 1*2 , 2개의 입력이 주어졌을때, 출력값, = 1*3    
    def predict(self, x):
        return np.dot(x, self.W)

    # 무게결과 값 후,, softmax로 변환후
    # 정답 vector와 손실률 비교,
    # one-shot 확률 모델,
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss
    


In [4]:
tmp = simpleNet()
print(tmp.W)
x = np.array([0.6,0.9])

p = tmp.predict(x)

print("\nPredic:\n",p)
np.argmax(p)  # 최대값의 인덱스
print("\nmax:\n",np.argmax(p),": ",p[np.argmax(p)])

# 정답 lable
t = np.array([0,0,1])
#loss func
lossf = tmp.loss(x,t)
print("\nloss val:")
print(lossf)

[[-1.73364549 -0.32397934  0.54643781]
 [ 0.38974889  1.48923678  0.05945051]]

Predic:
 [-0.6894133   1.14592551  0.38136814]

max:
 1 :  1.1459255053058492

loss val:
1.250125985809945


In [5]:
#f는 매개변수와 상관없이 x일때의 loss값을 반환
# !!!! 하지만 loss안에서 매번 weigth를 사용하여 계산한다..
f = lambda w : tmp.loss(x,t)

#손실 값을 알고 있으니 각 weight별로 편미분 값을 계산

#?? f()을 매개변수 값과 상관없이 놓으면 미분값이 달라지지 않을텐데 0이 어떻게 안나온거지?
#  tmp.loss는 weight를 매번 사용하여 계산하기 때문에 tmp.W값을 변화시키면 계속 변한다.
#  즉 +h만큼 올린 weight로 계산하면 weight의 변화율마다 손실함수의 편미분값을 구할 수 있다.
dW = numerical_gradient(f,tmp.W)
print(dW)

[[ 0.05891063  0.36920806 -0.42811869]
 [ 0.08836594  0.55381209 -0.64217803]]


In [4]:
print(f(tmp.W)) #1.1410246625416545
tmp_val = x[0]
h = 1e-4
tmp.W[0] = float(tmp_val) + h
print(f(tmp.W))
tmp.W[0] = tmp_val

#W가 변하면 predic값이 변하기 때문에 f에서 쓰는 매개변수가 더미이더라도
#각 편미분값들이 정해질 수 있다. loss는 softmax(x*W) - t   이다.
#gradient에서 W는 계속 변하고 있으므로 출력값이 달라진다.

0.34697647769252354
0.8364137825872542
