In [2]:
import numpy as np
import sys,os
sys.path.append(os.pardir)
from common.util import im2col

In [3]:
b = np.array([[[1,2,-1],
               [3,4,-2]],
              
              [[5,6,-3],
               [7,8,-4]]])
b.shape

(2, 2, 3)

In [4]:
b.max(1)

array([[ 3,  4, -1],
       [ 7,  8, -3]])

In [5]:
a = 3

a 
    


3

In [45]:
x = np.arange(10*1*784).reshape(10,1,28,28)
x.shape

(10, 1, 28, 28)

In [46]:
col = im2col(x,5,5,1,0)
col.shape

(5760, 25)

In [58]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
a[[1,2],[1,2]]

array([ 5, 10])

In [64]:
b = np.zeros((2,2,2,2))
b

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [70]:
b.shape + (1)

TypeError: can only concatenate tuple (not "int") to tuple